# Generated by Django 5.2.7 on 2025-10-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('logradouro', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=80)),
                ('numero', models.PositiveBigIntegerField(max_length=80)),
            ],
        ),
    ]
